language: node_js
node_js:
  - stable
cache: yarn
script: skip

after_success:
  - npm run test:coveralls
  - npm run build:storybook

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    keep_history: true
    local_dir: storybook-static
    on:
      branch: release
  - provider: npm
    email: baobobbob@outlook.com
    api_key: $NPM_TOKEN
    skip_cleanup: false
    script: npm run build
    on:
      branch: release

notifications:
  email:
    on_success: never
    on_failure: always
