language: node_js
node_js:
  - stable
cache: yarn
script: skip

after_success:
  - npm run test:coveralls
  - npm run build:storybook

#deploy:
#  - provider: pages
#    skip_cleanup: true
#    github_token: $GH_TOKEN
#    keep_history: true
#    local_dir: storybook-static
#    on:
#      branch: master
#      tags: true

jobs:
  include:
    - stage: release
      node_js: stable
      script: npm run build
      deploy:
        provider: script
        skip_cleanup: true
        script: npx -p @semantic-release/changelog -p @semantic-release/git -p semantic-release semantic-release
        on:
          branch: master
          tags: true

notifications:
  email:
    on_success: never
    on_failure: never
